/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyNativeClass */

#ifndef _Included_MyNativeClass
#define _Included_MyNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyNativeClass
 * Method:    myNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyNativeClass_myNativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
